### ISSUE TITLE
Importing ABC directly from collections module was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [Cito/PyGreSQL#13]
https://bugzilla.redhat.com/show_bug.cgi?id=1791750

https://github.com/Cito/PyGreSQL/blob/5d51d1d6dcb01d48f4260266330cb22c7a447bf5/tests/test_classic_connection.py#L21

**Comment by Cito** [comment]
Thank you for this contribution. Please be a bit patient - I'm currently waiting for the decision of the current project owner whether we can move the project to GitHub. The original SVN repository is currently not available and this repository was considered a read-only mirror only so far.

**Comment by tirkarthi** [comment]
No problem, thanks for the update.
