### ISSUE TITLE
encounter a problem when using pygresql

### ISSUE THREAD

**Issue by VoodooVoodoo** [Cito/pygresql#3]
hi, i encountered a problem when i was using pygresql to insert data(read from json file) into postgresql.
from pg import DB
DB.insert()

the problem is that memory cannot release and it raised very fast.

looking for your reply, thanks a lot

**Comment by Cito** [comment]
Which version of PyGreSQL did you use? One known problem has been fixed in version 5.0.1.

If you used a later version, can you provide a test case that shows the problem?

**Comment by VoodooVoodoo** [comment]
sorry for reply so late.
version is 5.03, here is my code:
db = Db(dbname='',host='',port='',user='',passwd='')
with open("") as f:
    rows=f.readline()
try:
    for i in rows:
         dic = json.loads(i)
         db.insert('tab_name',col1='',col='' .......)
except Exception:
        pass
finally:
        db.close()

when i load lots of json files, the memory cannot release. Did I used wrong function to close the connection, or other causes?
thank you for your reply!

**Comment by Cito** [comment]
Thanks, but we need actually working code with all the details. including definition of the database table to be able to reproduce it. Are you also using json or jsonb data type in the table? Also let us know your Python+Postgres versions. And please note that you need to indent code with 4 spaces in your comment to make it appear properly.

**Comment by VoodooVoodoo** [comment]
python 3.5 and postgresql 9.6
yes i used json and json[] data type in the table.
db = Db(dbname='',host='',port='',user='',passwd='')
with open("") as f:
    rows=f.readline()
try:
    for i in rows:
        dic = json.loads(i)
        db.insert('tab_name',col1='',col='' .......)
except Exception:
    pass
finally:
    db.close()
