### ISSUE TITLE
Licence Type

### ISSUE THREAD

**Issue by anubhav3itb** [Cito/pygresql#7]
Hi, I am planning to use this library for development purpose but not sure about is Licence type. Can someone please confirm its licence type or provide a link to something official documentation explaining it?

**Comment by Cito** [comment]
Hi @anubhav3itb. The [copyright notice](http://www.pygresql.org/copyright.html ) has the full text of the license. The license type is [PostgreSQL license](https://tldrlegal.com/license/postgresql-license-(postgresql)). I'll clarify this in the copyright notice and fix the entry in setup.py which says "Python license".

**Comment by Cito** [comment]
This has been fixed in SVN, will be set properly in next version.
